name: EnigMano Instance Deployment

on:
  workflow_dispatch:
    inputs:
      INSTANCE:
        description: "Instance number to deploy (e.g., 1, 2, 3...)"
        required: true
        default: "1"

jobs:
  deploy-enigmano:
    runs-on: windows-latest

    env:
      INSTANCE_ID: ${{ github.event.inputs.INSTANCE }}
      SECRET_SHAHZAIB: ${{ secrets.SECRET_SHAHZAIB }}
      NGROK_SHAHZAIB: ${{ secrets.NGROK_SHAHZAIB }}
      RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}   # Optional: provide this if EnigMano doesn’t set a password
      BOT_ZIP_URL: "https://www.dropbox.com/scl/fi/gmvwihaldwpl0kgswvxdo/bot.zip?rlkey=42hs0lk9kjh1a6g57zkwfocpz&st=i1ld0nyk&dl=1"

    steps:
      - name: Deployment Parameters
        shell: pwsh
        run: |
          $prevInstance = [int]$env:INSTANCE_ID - 1
          Write-Host "==============================================="
          Write-Host "Instance ID          : $env:INSTANCE_ID"
          Write-Host "Previous Instance    : $prevInstance"
          Write-Host "Repository           : $env:GITHUB_REPOSITORY"
          Write-Host "Workflow File        : enigmano.yml"
          Write-Host "Deployment ID        : $env:GITHUB_RUN_ID"
          Write-Host "==============================================="

      - name: Validate Secrets
        shell: pwsh
        run: |
          if (-not $env:NGROK_SHAHZAIB) { Write-Error "Missing Ngrok Auth Token: NGROK_SHAHZAIB"; exit 1 }
          Write-Host "Secrets OK"

      - name: Enable RDP and set password (optional)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          # Enable RDP
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop" | Out-Null
          # Set password if provided
          if ($env:RDP_PASSWORD) {
            Write-Host "Setting runneradmin password from secret..."
            net user runneradmin "$env:RDP_PASSWORD" | Out-Null
          } else {
            Write-Host "No RDP_PASSWORD secret provided. Assuming another script sets it."
          }
          Write-Host "RDP enabled."

      - name: Install ngrok CLI
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $ngrokDir = "C:\Users\runneradmin\ngrok"
          $ngrokExe = Join-Path $ngrokDir "ngrok.exe"
          if (-not (Test-Path $ngrokExe)) {
            New-Item -ItemType Directory -Force -Path $ngrokDir | Out-Null
            $zip = Join-Path $ngrokDir "ngrok.zip"
            Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip" -OutFile $zip -UseBasicParsing
            Expand-Archive -Path $zip -DestinationPath $ngrokDir -Force
            Remove-Item $zip -Force
          }
          & $ngrokExe version

      - name: Authenticate ngrok
        shell: pwsh
        run: |
          $ngrokExe = "C:\Users\runneradmin\ngrok\ngrok.exe"
          & $ngrokExe config add-authtoken $env:NGROK_SHAHZAIB

      - name: ngrok TCP diagnostic (print exact error if it can’t start)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $ngrokExe = "C:\Users\runneradmin\ngrok\ngrok.exe"
          $diagLog = "C:\Users\runneradmin\ngrok\diag.log"
          if (Test-Path $diagLog) { Remove-Item -LiteralPath $diagLog -Force -ErrorAction SilentlyContinue }
          # Start once, write to diag.log, run ~8 seconds, then kill if still alive
          $p = Start-Process -FilePath $ngrokExe -ArgumentList 'tcp 3389 --log=stdout --log-level=debug' -RedirectStandardOutput $diagLog -PassThru -WindowStyle Hidden
          Start-Sleep -Seconds 8
          if (-not $p.HasExited) { Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue }
          Write-Host "=== ngrok diagnostic log (last 100 lines) ==="
          if (Test-Path $diagLog) {
            Get-Content -LiteralPath $diagLog -Tail 100
          } else {
            Write-Host "No diag log produced (ngrok may have exited immediately)."
          }
          Write-Host "============================================="
          # Do not fail the job here; this is diagnostics only.

      - name: Start resilient ngrok TCP tunnel (monitored)
        shell: pwsh
        env:
          GITHUB_STEP_SUMMARY: ${{ github.step_summary }}
        run: |
          $ErrorActionPreference = 'Stop'
          $ngrokExe = "C:\Users\runneradmin\ngrok\ngrok.exe"
          $logFile  = "C:\Users\runneradmin\ngrok\ngrok.log"
          $urlFile  = "C:\Users\runneradmin\ngrok\ngrok-url.txt"
          if (Test-Path $logFile) { Remove-Item $logFile -Force -ErrorAction SilentlyContinue }
          if (Test-Path $urlFile) { Remove-Item $urlFile -Force -ErrorAction SilentlyContinue }

          function Start-Ngrok {
            param([string]$Args = "tcp 3389 --log=`"$logFile`" --log-format=logfmt --log-level=info")
            $psi = New-Object System.Diagnostics.ProcessStartInfo
            $psi.FileName = $ngrokExe
            $psi.Arguments = $Args
            $psi.UseShellExecute = $true
            $psi.CreateNoWindow = $true
            [System.Diagnostics.Process]::Start($psi) | Out-Null
          }

          Start-Ngrok
          Write-Host "ngrok started."

          $monitorMinutes = 20     # shorter monitor here; the long hold is later
          $pollSeconds    = 3
          $loops          = [Math]::Ceiling(($monitorMinutes*60) / $pollSeconds)
          $currentUrl     = $null

          for ($i = 1; $i -le $loops; $i++) {
            Start-Sleep -Seconds $pollSeconds
            if (Test-Path $logFile) {
              $txt = Get-Content -LiteralPath $logFile -Raw -ErrorAction SilentlyContinue
              if ($txt -match 'tcp://[0-9a-zA-Z\.-]+:\d+') {
                $found = $Matches[0]
                if ($found -ne $currentUrl) {
                  $currentUrl = $found
                  Set-Content -LiteralPath $urlFile -Value $currentUrl -Encoding ASCII
                  Write-Host ("[ngrok] RDP address: {0}" -f $currentUrl)
                  Add-Content -LiteralPath $env:GITHUB_STEP_SUMMARY -Value ("## RDP (ngrok)\n\n- Address: `{0}`\n- Username: `runneradmin`\n- Password: use the one set above\n\n" -f $currentUrl)
                }
              }
            }
            $running = Get-Process -Name ngrok -ErrorAction SilentlyContinue
            if (-not $running) {
              Write-Host "ngrok not running; restarting..."
              if (Test-Path $logFile) { Remove-Item $logFile -Force -ErrorAction SilentlyContinue }
              Start-Ngrok
              $currentUrl = $null
            }
          }
          Write-Host "ngrok short monitor finished (URL shown above if available)."

      - name: Download and extract Bot to C:\Users\runneradmin\Downloads\Bot
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

          $BOT_BASE = "C:\Users\runneradmin\Downloads\Bot"
          $downloads = "C:\Users\runneradmin\Downloads"

          New-Item -ItemType Directory -Force -Path $downloads | Out-Null
          New-Item -ItemType Directory -Force -Path $BOT_BASE | Out-Null

          $tmp = Join-Path $env:TEMP ('botdl_' + [guid]::NewGuid())
          New-Item -ItemType Directory -Force -Path $tmp | Out-Null

          try {
            $zipPath = Join-Path $tmp 'bot.zip'
            Write-Host ("Downloading Bot.zip from {0} ..." -f $env:BOT_ZIP_URL)
            Invoke-WebRequest -Uri $env:BOT_ZIP_URL -OutFile $zipPath -UseBasicParsing

            $extract = Join-Path $tmp 'unzipped'
            Expand-Archive -Path $zipPath -DestinationPath $extract -Force

            $candidates = @(
              (Join-Path $extract 'Bot'),
              (Join-Path $extract 'bot')
            ) | Where-Object { Test-Path $_ }

            if ($candidates.Count -gt 0) {
              $root = $candidates[0]
              Write-Host ("Found root folder in archive: {0}" -f $root)
              Copy-Item -Path (Join-Path $root '*') -Destination $BOT_BASE -Recurse -Force
            } else {
              Write-Host "No root 'Bot' folder; copying all extracted files into BOT_BASE"
              Copy-Item -Path (Join-Path $extract '*') -Destination $BOT_BASE -Recurse -Force
            }

            Write-Host "Downloads directory listing:"
            Get-ChildItem -Force $downloads | Select-Object Name,Length,LastWriteTime | Format-Table -AutoSize
            Write-Host "Bot directory listing:"
            Get-ChildItem -Force $BOT_BASE | Select-Object Name,Length,LastWriteTime | Format-Table -AutoSize

          } finally {
            try { Remove-Item -LiteralPath $tmp -Recurse -Force -ErrorAction SilentlyContinue } catch {}
          }

      - name: Launch bots (start-bots.bat)
        shell: pwsh
        run: |
          $BOT_BASE = "C:\Users\runneradmin\Downloads\Bot"
          $bat = Join-Path $BOT_BASE 'start-bots.bat'
          if (-not (Test-Path $bat)) { throw ("start-bots.bat not found at {0}" -f $bat) }
          Write-Host "Launching bots via start-bots.bat ..."
          $psi = New-Object System.Diagnostics.ProcessStartInfo
          $psi.FileName = $bat
          $psi.WorkingDirectory = $BOT_BASE
          $psi.UseShellExecute = $true
          $psi.WindowStyle = 'Normal'
          [void][System.Diagnostics.Process]::Start($psi)

      - name: Keep session open (fixed window, heartbeat)
        shell: pwsh
        run: |
          $minutes = 180
          $interval = 20
          $loops = [Math]::Ceiling(($minutes * 60) / $interval)
          Write-Host ("Holding session open for {0} minutes with {1}s heartbeat..." -f $minutes, $interval)
          for ($i = 1; $i -le $loops; $i++) {
            if (Test-Path "C:\Users\runneradmin\ngrok\ngrok-url.txt") {
              $url = Get-Content "C:\Users\runneradmin\ngrok\ngrok-url.txt" -ErrorAction SilentlyContinue
              if ($url) { Write-Host ("Current RDP URL: {0}" -f $url) }
            }
            Write-Host ("Heartbeat {0}/{1}  (remaining ~{2} min)" -f $i, $loops, [Math]::Round(($loops - $i) * $interval / 60.0, 1))
            Start-Sleep -Seconds $interval
          }
          Write-Host "Fixed hold complete."

      - name: Upload ngrok URL file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ngrok-url
          path: C:\Users\runneradmin\ngrok\ngrok-url.txt
          if-no-files-found: warn

      - name: Final Status
        if: always()
        shell: pwsh
        run: |
          Write-Host ("Pipeline finished for instance {0}." -f $env:INSTANCE_ID)
